### ISSUE TITLE
Add Apptron

### ISSUE THREAD

**Issue by 1j01** [go-graphics/go-gui-projects#19]
[Apptron](https://github.com/tractordev/apptron) is an upcoming cross-platform framework with modules for webview windows, menus, notifications, global shortcuts, etc.

It's also designed to make these functionalities available to shell scripts, which is interesting. It has a nice philosophy to it.

**Comment by zigo101** [comment]
@1j01 

Thanks for recommendation. I just checked the project page of Apptron. It looks it is HTML based, right?

**Comment by 1j01** [comment]
Yes, I would categorize it as HTML based.

**Comment by zigo101** [comment]
Okay, just added it.
