### ISSUE TITLE
Add Qlovaseed

### ISSUE THREAD

**Issue by Splizard** [go-graphics/go-gui-projects#2]
(github.com/qlova/seed)

Qlovaseed is an WIP app-development framework leveraging web technologies to build apps.
GUI's can be created by combining and styling seeds (widgets).

**Comment by go101** [comment]
Could you introduce it more? How does the UI is presented? I couldn't find the info from the project.
More specifically: doesn't it embed browsers? or use the installed browsers directly?

**Comment by go101** [comment]
Added it, and described it as "doesn't bundle browsers".  Please let me know if this is not correct.

**Comment by Splizard** [comment]
Cheers, that's correct. The framework leverages existing browsers when run locally or can be remotely served as a progressive web application.
